### ISSUE TITLE
[Devops] Setup Dockerfile with SQL Server

### ISSUE THREAD

**Issue by lcaohoanq** [lcaohoanq/Clothes-Shop#51]

**Comment by lcaohoanq** [comment]
![image](https://github.com/user-attachments/assets/81e5ce41-dfc9-4194-8cf8-51e8100084e8)

### docker-compose.yml
```yml
version: '3.8'

volumes:
  sqlserver_data:
  
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:-Luucaohoang1604^^} #use - to escape special character
      - MSSQL_PID=Developer
    ports:
      - 1434:1433 
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-password123} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SA_PASSWORD:-Luucaohoang1604^^} -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '
```
### init/init.sql

```sql
USE [master];
GO

IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'newuser')
BEGIN
    CREATE LOGIN [newuser] WITH PASSWORD = 'password123', CHECK_POLICY = OFF;
    ALTER SERVER ROLE [sysadmin] ADD MEMBER [newuser];
END
GO
```

### .env

```text
SA_PASSWORD=Luucaohoang1604^^
```
